### PR TITLE
tf5server: add ListResource RPC

### PR DESCRIPTION
**Pull request by bbasata**
## Related Issue

Fixes # 

## Description

In plain English, describe your approach to addressing the issue linked above. For example, if you made a particular design decision, let us know why you chose this path instead of another solution.

## Rollback Plan

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: cmd/terraform-provider-primes/README.md [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+            "type": "Im51bWJlciI=",
+            "description": "n"
+          }
+        ]
+      }
+    }
+  }
+}
+
+$ grpcurl -plaintext $(cmd/terraform-provider-primes/reattach.sh) tfplugin5.Provider.ListResource
```
Comment (bbasata) [inline cmd/terraform-provider-primes/README.md:45]: cc: @dbanck

**Comment by bbasata** [comment]
Checks fail in the same way they do in #514. @rainkwan to 💭 with @austinvalle on whether a temporary interface is the way to go here or not.

**Comment by austinvalle** [comment]
> Checks fail in the same way they do in #514. @rainkwan to 💭 with @austinvalle on whether a temporary interface is the way to go here or not.

Yeah temporary interfaces are good to use here to avoid the compilation errors. I'll write up a small blurb in this repo, but the general thing we need to avoid are temporary interfaces on global RPCs that Terraform uses the unimplemented GRPC code to determine if a provider supports the RPC.

That kind of RPC rarely pops up, and in the case of list, these RPCs aren't going to be reachable by today's workflows so  temporary is good 👍🏻
